version: '3.7'

services:
  licensingservice:
    image: aangdocker/licensing-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_APPLICATION_NAME=licensing-service
      - SPRING_CLOUD_CONFIG_URI=http://configservice:8071

networks:
  default:
    external: true
    name: config-server-dockersied_config-server-network